updated script to execute perform pearson correlation for year vs rating and complexity vs rating

diff --git a/analysis b/analysis
--- a/analysis
+++ b/analysis
@@ -4,7 +4,7 @@
 
 #check input file validation
 if [ -z "$1" ]; then
-	echo "Please use $0 <fileName.tsv"
+	echo "Please use $0 <fileName.tsv>"
 	exit 1
 fi
 
@@ -17,7 +17,8 @@ awk -F'\t' '
 			if ( tolower($i) == "domains" ) domains_col=i
 			if ( tolower($i) == "mechanics" ) mechanics_col=i
 			if ( tolower($i) == "year published" ) year_col=i
-			if ( tolower($i) == "rating average") rating_col=i
+			if ( tolower($i) == "rating average" ) rating_col=i
+			if ( tolower($i) == "complexity average" ) complexity_col=i
 		}
 
 		#handle error in case the required columns are nor present in the dataset
@@ -35,6 +36,10 @@ awk -F'\t' '
 		}
 		if ( !rating_col ) {
 			print "Error : Missing Average rating column in the dataset"
+			exit 1
+		}
+		if ( !complexity_col ) {
+			print "Error : Missing Complexity Average column in the dataset"
 			exit 1
 		}
 
@@ -63,8 +68,8 @@ awk -F'\t' '
 		m = split($(mechanics_col),mechanics,",")
 
 		for ( i = 1; i <= m; i++ ) {
-			#check is the mechnic is not an empty string
-			if ( mechanics[i] != "") {
+			#check is the mechanic is not an empty string
+			if ( mechanics[i] != "" ) {
 				#trim leading/trailing spaces
 				gsub(/^[ \t]+|[ \t]+$/, "", mechanics[i])
 				#increment the count for each mechanic encountered
@@ -73,10 +78,12 @@ awk -F'\t' '
 		}
 
 		#calculate inputs for pearson correlation formula
-		year=$(year_col)
-		rating=$(rating_col)
+		year = $(year_col)
+		rating = $(rating_col)
+		complexity = $(complexity_col)
 
-		#let's consider x as varibale year and y as varibale rating
+		#year vs rating correlation
+		#lets consider x as variable year and y as variable rating
 		if ( year != "" && rating != "" ) {
 			num++
 			sum_x += year
@@ -84,6 +91,17 @@ awk -F'\t' '
 			sum_x_squared += year * year
 			sum_y_squared += rating * rating
 			sum_xy += year * rating
+		}
+
+		#complexity vs rating correlation
+		#lets consider c as variable complexity and r as variable rating
+		if ( complexity != "" && rating != "" ) {
+			num_points++
+			sum_c += complexity
+			sum_r += rating
+			sum_c_squared += complexity * complexity
+			sum_r_squared += rating * rating
+			sum_cr += complexity * rating
 		}
 	}
 
@@ -108,5 +126,28 @@ awk -F'\t' '
 		}
 		printf("The most popular game mechanics is %s found in %d games\n", max_mechanic, max_mechanic_count)
 		printf("The most game domian is %s found in %d games\n", max_domain, max_domain_count)
+
+		#execute pearson correlation formula for  year published vs rating
+		numerator = ( num * sum_xy ) - ( sum_x * sum_y )
+		denominator = sqrt((num * sum_x_squared - sum_x^2) * (num * sum_y_squared - sum_y^2))
+
+		#check if denominator is zero to avoid zero devision error
+		if (denominator == 0) {
+			print "Can not perform pearson corrlation due to denominator being zero"
+		} else {
+			correlation = numerator/denominator
+			printf("The correlation between the year of publication and the average rating is %.3f\n", correlation)
+		}
+
+		#execute pearson correlation formula for complexity vs rating
+		numerator = ( num_points * sum_cr ) - ( sum_c * sum_r )
+		denominator = sqrt((num_points * sum_c_squared - sum_c^2) * (num_points * sum_r_squared - sum_r^2))
+
+		if (denominator == 0) {
+			print "Can not perform pearson corrleation due to denominator being zero"
+		} else {
+			correlation = numerator/denominator
+			printf("The correlation between the complexity of a game and its average rating is %.3f\n", correlation)
+		}
 	}
 ' "$input_file"
